jobs:
  lighthouse:
    docker:
      - image: circleci/node:12.18.3-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - run: sudo yarn global add @lhci/cli@0.4.4
      - run: lhci autorun

orbs:
  node: circleci/node@3.0.1
version: 2.1
workflows:
  test:
    jobs:
      - lighthouse
